DROP TABLE IF EXISTS user;
CREATE TABLE user
(
    id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	birthday datetime NULL DEFAULT NULL COMMENT '生日',
	user_type VARCHAR(50) NULL DEFAULT NULL COMMENT '用户类型',
	deleted tinyint(2) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0:未删除 1: 已删除',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (id)
);


DROP TABLE IF EXISTS product;
CREATE TABLE product
(
    id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	user_Id bigint(20) NULL DEFAULT NULL COMMENT '用户id',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '商品名',
	amount int(1) NULL DEFAULT NULL COMMENT '金额',
	order_date datetime NULL DEFAULT NULL COMMENT '下单日期',
	deleted tinyint(2) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0:未删除 1: 已删除',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (id)
);